from django.contrib import admin
from models import *

admin.site.register(Manufacturer)
admin.site.register(ManufacturerModel)
admin.site.register(EmployeeWithdrawn)
admin.site.register(RepairShop)
admin.site.register(Shop)
admin.site.register(Machine)
admin.site.register(Implement)
admin.site.register(Employee)
admin.site.register(EmployeeAttendance)
admin.site.register(Qualification)
admin.site.register(Certification)
admin.site.register(EmployeeQualifications)
admin.site.register(EmployeeCertifications)
admin.site.register(MachineQualification)
admin.site.register(MachineCertification)
admin.site.register(ImplementQualification)
admin.site.register(ImplementCertification)
admin.site.register(Field)
admin.site.register(GPS)
admin.site.register(FieldLocalization)
admin.site.register(EmployeeLocalization)
admin.site.register(TaskCategory)
admin.site.register(Task)
admin.site.register(EmployeeTask)
admin.site.register(TaskImplementMachine)
admin.site.register(Appendix)
admin.site.register(AppendixTask)
admin.site.register(ServiceCategory)
admin.site.register(MachineService)
admin.site.register(ImplementService)
admin.site.register(Question)
admin.site.register(EquipmentCategory)
admin.site.register(EquipmentType)
admin.site.register(ImplementChecklist)
admin.site.register(MachineChecklist)
# Register your models here.)
