"""
Django settings for heavyconnect project.

Generated by 'django-admin startproject' using Django 1.8.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
from django.utils.translation import ugettext_lazy as _

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'dgaaxm0o4)7max48$chs1im)av623&qw^t*e4evk8m*@48al3^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False


ALLOWED_HOSTS = [
    '*'
    ]

SHARED_APPS = (
    'tenant_schemas',  # mandatory
    'home', # you must list the app where your tenant model resides in
    'django.contrib.contenttypes',

)

TENANT_APPS = (
    # The following Django contrib apps must be in TENANT_APPS
    'django.contrib.contenttypes',
    # your tenant-specific apps
    # 'home',
)

TENANT_MODEL = "home.Client"
# Application definition

INSTALLED_APPS = list(SHARED_APPS) + [
    'django.contrib.admin',
    'django.contrib.auth',
    # 'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 'home',
    'easy_pdf',
]

ADMINS = [('Jessica', 'jgon91@gmail.com')]
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'jgon91@gmail.com'
EMAIL_HOST_PASSWORD = os.environ['EMAIL_PASS']
SERVER_EMAIL = 'jgon91@gmail.com'
MANAGERS = ADMINS
EMAIL_USE_TLS = True

MIDDLEWARE_CLASSES = (
    'tenant_schemas.middleware.TenantMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.common.BrokenLinkEmailsMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.locale.LocaleMiddleware',

)

ROOT_URLCONF = 'heavyconnect.urls'

PROJECT_ROOT = os.path.abspath(os.path.dirname(__file__))

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(PROJECT_ROOT, '../templates').replace('\\','/'),],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',
            ],
        },
    },
]

WSGI_APPLICATION = 'heavyconnect.wsgi.application'


# DATABASES = {
#          'default': {
#              'ENGINE': 'tenant_schemas.postgresql_backend', # Add 'postgresql_psycopg2', 'mysql', 'sqlite3' or 'oracle'.
#              'NAME': 'dev',                      # Or path to database file if using sqlite3.
#              'USER': '',                      # Not used with sqlite3.
#              'PASSWORD': '',                  # Not used with sqlite3.
#              'HOST': 'localhost',                      # Set to empty string for localhost. Not used with sqlite3.
#              'PORT': '5432',                      # Set to empty string for default. Not used with sqlite3.
#
#          }
#      }
DATABASES = {
    'default': {
        'ENGINE': 'tenant_schemas.postgresql_backend',
        'NAME': os.environ['DB_NAME'],                      # Or path to database file if using sqlite3.
        'USER': os.environ['DB_USER'],                      # Not used with sqlite3.
        'PASSWORD': os.environ['DB_PASS'],                  # Not used with sqlite3.
        'HOST': os.environ['DB_HOST'],                      # Set to empty string for localhost. Not used with sqlite3.
        'PORT': os.environ['DB_PORT'],
    }
}

#tanda
# DATABASES = {
#     'default': {
#         'ENGINE': 'tenant_schemas.postgresql_backend',
#         'NAME': 'd395pa1l0s6i0g',                      # Or path to database file if using sqlite3.
#         'USER': 'dntkrypwpilsae',                      # Not used with sqlite3.
#         'PASSWORD': 'QAUjydqmetOvNSew_L1c309zd6',                  # Not used with sqlite3.
#         'HOST': 'ec2-54-204-12-25.compute-1.amazonaws.com',                      # Set to empty string for localhost. Not used with sqlite3.
#         'PORT': '5432',
#     }
# }

DATABASE_ROUTERS = (
    'tenant_schemas.routers.TenantSyncRouter',
)

TEMPLATE_CONTEXT_PROCESSORS = (
    'django.core.context_processors.request',
)
# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

MEDIA_ROOT = os.path.join(PROJECT_ROOT, '../static/media')

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'US/Pacific'

USE_I18N = True

USE_L10N = True

USE_TZ = False

LANGUAGES = (
    ('en-us', _('English')),
    ('es', _('Spanish')),
    ('pt-br', _('Brazilian Portuguese')),
)

LOCALE_PATHS = (
    os.path.join(BASE_DIR, 'locale/'),
)

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_ROOT = 'importStatic/'   

STATIC_URL = '/static/'

MEDIA_URL = '/media/'


STATICFILES_DIRS = (
    os.path.join(PROJECT_ROOT, '../static').replace('\\','/'),
)
