# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appendix',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('a_type', models.CharField(max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AppendixTask',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('quantity', models.IntegerField()),
                ('brand', models.CharField(max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('appendix', models.ForeignKey(to='home.Appendix')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceChecklist',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('category', models.IntegerField(choices=[(1, b'Always'), (2, b'Less lunch than Expected'), (3, b'Less Breaks than Expected'), (4, b'Optional Lunch')])),
                ('description', models.CharField(max_length=2000)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Beacon',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('beacon_serial', models.CharField(max_length=10, null=True)),
                ('refers', models.IntegerField(choices=[(1, b'Machine'), (2, b'Implement')])),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BeaconGPS',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('timestamp', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('beacon', models.ForeignKey(to='home.Beacon')),
            ],
        ),
        migrations.CreateModel(
            name='Break',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('lunch', models.BooleanField()),
                ('edited', models.BooleanField(default=False)),
                ('start', models.TimeField()),
                ('end', models.TimeField(null=True, blank=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('description', models.CharField(max_length=50)),
                ('year', models.IntegerField(null=True, blank=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyStatus',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('active', models.BooleanField(default=True)),
                ('employ_limit', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='ConfirmationCheck',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('answer', models.BooleanField()),
                ('note', models.CharField(max_length=200, blank=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('active', models.BooleanField(default=True)),
                ('company_id', models.CharField(max_length=10, null=True, blank=True)),
                ('language', models.IntegerField(default=3, choices=[(1, b'pt-br'), (2, b'es'), (3, b'en-us')])),
                ('qr_code', models.CharField(max_length=10, null=True, blank=True)),
                ('start_date', models.DateField(null=True, blank=True)),
                ('hour_cost', models.FloatField(null=True, blank=True)),
                ('contact_number', models.CharField(max_length=14, blank=True)),
                ('permission_level', models.IntegerField(default=1, choices=[(1, b'Driver'), (2, b'Manager'), (3, b'Shop')])),
                ('notes', models.CharField(max_length=250, null=True, blank=True)),
                ('teamManager', models.BooleanField(default=False)),
                ('photoEmployee', models.ImageField(default=b'employee/no.jpg', upload_to=b'employee')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('manager', models.ForeignKey(blank=True, to='home.Employee', null=True)),
                ('user', models.OneToOneField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeAttendance',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('date', models.DateField()),
                ('hour_started', models.TimeField()),
                ('hour_ended', models.TimeField(null=True, blank=True)),
                ('signature', models.CharField(max_length=5000, null=True, blank=True)),
                ('edited', models.BooleanField(default=False)),
                ('hours_worked', models.TimeField(null=True, blank=True)),
                ('declined', models.BooleanField(default=False)),
                ('manager_rejected', models.BooleanField(default=False)),
                ('manager_approved', models.BooleanField(default=False)),
                ('manager', models.CharField(default=b'', max_length=5000, null=True, blank=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('employee', models.ForeignKey(to='home.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeAttendanceChecklist',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('answer', models.CharField(max_length=200, blank=True)),
                ('attendance', models.ForeignKey(to='home.EmployeeAttendance')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeCertifications',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('certification', models.ForeignKey(to='home.Certification')),
                ('employee', models.ForeignKey(to='home.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeLocalization',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('e_time', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('employee', models.ForeignKey(to='home.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeQualifications',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('level', models.IntegerField(choices=[(1, b'Low'), (2, b'Medium'), (3, b'High')])),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('employee', models.ForeignKey(to='home.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeTask',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('start_time', models.DateTimeField(null=True, blank=True)),
                ('end_time', models.DateTimeField(null=True, blank=True)),
                ('hours_spent', models.FloatField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('employee', models.ForeignKey(to='home.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeWithdrawn',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('date', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('employee', models.ForeignKey(to='home.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentCategory',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=25)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=25)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('category', models.ForeignKey(to='home.EquipmentCategory')),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=50)),
                ('organic', models.BooleanField()),
                ('size', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FieldLocalization',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('field', models.ForeignKey(to='home.Field')),
            ],
        ),
        migrations.CreateModel(
            name='GPS',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('permanent', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('creator', models.ForeignKey(to='home.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='GroupParticipant',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('group', models.ForeignKey(to='home.Group')),
                ('participant', models.ForeignKey(to='home.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Implement',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('nickname', models.CharField(max_length=20)),
                ('qr_code', models.CharField(max_length=10, null=True, blank=True)),
                ('asset_number', models.CharField(max_length=15)),
                ('serial_number', models.CharField(max_length=25)),
                ('horse_power_req', models.IntegerField(null=True, blank=True)),
                ('hitch_capacity_req', models.IntegerField(null=True, blank=True)),
                ('hitch_category', models.IntegerField(blank=True, null=True, choices=[(1, b'1'), (2, b'2'), (3, b'3'), (4, b'4N'), (5, b'4'), (6, b'5')])),
                ('drawbar_category', models.IntegerField(blank=True, null=True, choices=[(1, b'1'), (2, b'2'), (3, b'3'), (4, b'4'), (5, b'4WS'), (6, b'5'), (7, b'5WS')])),
                ('speed_range_min', models.FloatField(null=True, blank=True)),
                ('speed_range_max', models.FloatField(null=True, blank=True)),
                ('year_purchased', models.IntegerField(null=True, blank=True)),
                ('implement_hours', models.IntegerField(null=True, blank=True)),
                ('service_interval', models.IntegerField(null=True, blank=True)),
                ('base_cost', models.FloatField(null=True, blank=True)),
                ('hour_cost', models.FloatField(null=True, blank=True)),
                ('status', models.IntegerField(choices=[(1, b'Ok'), (2, b'Attention'), (3, b'Broken'), (4, b'Quarantine')])),
                ('photo', models.URLField(null=True, blank=True)),
                ('photo1', models.URLField(null=True, blank=True)),
                ('photo2', models.URLField(null=True, blank=True)),
                ('note', models.CharField(max_length=250, null=True, blank=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('beacon', models.ForeignKey(blank=True, to='home.Beacon', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImplementCertification',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('certification', models.ForeignKey(to='home.Certification')),
                ('implement', models.ForeignKey(to='home.Implement')),
            ],
        ),
        migrations.CreateModel(
            name='ImplementChecklist',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('answer', models.BooleanField()),
                ('note', models.CharField(max_length=200, blank=True)),
                ('date', models.DateTimeField()),
                ('photo', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('employee', models.ForeignKey(blank=True, to='home.Employee', null=True)),
                ('qr_code', models.ForeignKey(to='home.Implement')),
            ],
        ),
        migrations.CreateModel(
            name='ImplementQualification',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('qualification_required', models.IntegerField(choices=[(1, b'Low'), (2, b'Medium'), (3, b'High')])),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('implement', models.ForeignKey(to='home.Implement')),
            ],
        ),
        migrations.CreateModel(
            name='ImplementService',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('description', models.CharField(max_length=200)),
                ('assigned_date', models.DateTimeField()),
                ('expected_date', models.DateTimeField()),
                ('accomplished_date', models.DateTimeField(null=True, blank=True)),
                ('price', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('implement', models.ForeignKey(to='home.Implement')),
            ],
        ),
        migrations.CreateModel(
            name='ImplementTask',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('implement', models.ForeignKey(to='home.Implement')),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('nickname', models.CharField(max_length=20)),
                ('qr_code', models.CharField(max_length=10, null=True, blank=True)),
                ('asset_number', models.CharField(max_length=15)),
                ('serial_number', models.CharField(max_length=25, null=True, blank=True)),
                ('horsepower', models.IntegerField(null=True, blank=True)),
                ('hitch_capacity', models.IntegerField(null=True, blank=True)),
                ('hitch_category', models.IntegerField(blank=True, null=True, choices=[(1, b'1'), (2, b'2'), (3, b'3'), (4, b'4N'), (5, b'4'), (6, b'5')])),
                ('drawbar_category', models.IntegerField(blank=True, null=True, choices=[(1, b'1'), (2, b'2'), (3, b'3'), (4, b'4'), (5, b'4WS'), (6, b'5'), (7, b'5WS')])),
                ('speed_range_min', models.FloatField(null=True, blank=True)),
                ('speed_range_max', models.FloatField(null=True, blank=True)),
                ('year_purchased', models.IntegerField(null=True, blank=True)),
                ('engine_hours', models.IntegerField(null=True, blank=True)),
                ('service_interval', models.IntegerField(null=True, blank=True)),
                ('base_cost', models.FloatField(null=True, blank=True)),
                ('m_type', models.CharField(blank=True, max_length=1, null=True, choices=[(b'T', b'Track'), (b'W', b'Wheels')])),
                ('front_tires', models.CharField(max_length=20, null=True, blank=True)),
                ('rear_tires', models.CharField(max_length=20, null=True, blank=True)),
                ('steering', models.CharField(blank=True, max_length=1, null=True, choices=[(b'M', b'Manual'), (b'G', b'GPS')])),
                ('operator_station', models.CharField(blank=True, max_length=1, null=True, choices=[(b'a', b'Cab'), (b'b', b'Open'), (b'c', b'Canopy')])),
                ('status', models.IntegerField(default=1, choices=[(1, b'Ok'), (2, b'Attention'), (3, b'Broken'), (4, b'Quarantine')])),
                ('hour_cost', models.FloatField(null=True, blank=True)),
                ('photo', models.URLField(null=True, blank=True)),
                ('photo1', models.URLField(null=True, blank=True)),
                ('photo2', models.URLField(null=True, blank=True)),
                ('note', models.CharField(max_length=250, null=True, blank=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('beacon', models.ForeignKey(blank=True, to='home.Beacon', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MachineCertification',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('certification', models.ForeignKey(to='home.Certification')),
                ('machine', models.ForeignKey(to='home.Machine')),
            ],
        ),
        migrations.CreateModel(
            name='MachineChecklist',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('answer', models.BooleanField()),
                ('note', models.CharField(max_length=200, blank=True)),
                ('date', models.DateTimeField()),
                ('photo', models.TextField(max_length=550000, blank=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('employee', models.ForeignKey(blank=True, to='home.Employee', null=True)),
                ('qr_code', models.ForeignKey(to='home.Machine')),
            ],
        ),
        migrations.CreateModel(
            name='MachineQualification',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('qualification_required', models.IntegerField(choices=[(1, b'Low'), (2, b'Medium'), (3, b'High')])),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('machine', models.ForeignKey(to='home.Machine')),
            ],
        ),
        migrations.CreateModel(
            name='MachineService',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('description', models.CharField(max_length=200)),
                ('assigned_date', models.DateTimeField()),
                ('expected_date', models.DateTimeField()),
                ('accomplished_date', models.DateTimeField(null=True, blank=True)),
                ('price', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('machine', models.ForeignKey(to='home.Machine')),
            ],
        ),
        migrations.CreateModel(
            name='MachineTask',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('employee_task', models.ForeignKey(to='home.EmployeeTask')),
                ('machine', models.ForeignKey(to='home.Machine')),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ManufacturerModel',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('model', models.CharField(max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('manufacturer', models.ForeignKey(to='home.Manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('description', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('description', models.CharField(max_length=250)),
                ('category', models.IntegerField(choices=[(1, b'Default'), (2, b'Before Lunch Break'), (3, b'Post Lunch Pre Start'), (4, b'Post Lunch Start'), (5, b'End of Day Inspection'), (6, b'End of shift')])),
                ('refers', models.IntegerField(choices=[(1, b'Machine'), (2, b'Implement'), (3, b'Employee')])),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RepairShop',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=20)),
                ('number', models.CharField(max_length=14)),
                ('address', models.CharField(max_length=150)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('service_category', models.CharField(max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=20)),
                ('number', models.CharField(max_length=14)),
                ('address', models.CharField(max_length=150)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('field', models.CharField(default=0, max_length=100, null=True)),
                ('code', models.CharField(default=0, max_length=100, null=True)),
                ('rate_cost', models.FloatField(default=0, null=True)),
                ('date_assigned', models.DateTimeField(null=True)),
                ('hours_prediction', models.FloatField(default=0, null=True)),
                ('description', models.CharField(max_length=500, null=True)),
                ('passes', models.IntegerField(default=0, null=True)),
                ('task_init', models.DateTimeField(null=True, blank=True)),
                ('task_end', models.DateTimeField(null=True, blank=True)),
                ('hours_spent', models.FloatField(default=0, null=True)),
                ('pause_start', models.DateTimeField(null=True, blank=True)),
                ('pause_end', models.DateTimeField(null=True, blank=True)),
                ('pause_total', models.FloatField(null=True, blank=True)),
                ('status', models.IntegerField(default=1, null=True, choices=[(1, b'Pending'), (2, b'Approved'), (3, b'Denied'), (4, b'Ongoing'), (5, b'Paused'), (6, b'Finished')])),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('attendance', models.ForeignKey(to='home.EmployeeAttendance', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskCategory',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('description', models.CharField(max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskCode',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('category', models.ForeignKey(to='home.TaskCategory')),
            ],
        ),
        migrations.CreateModel(
            name='TimeKeeperRules',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('hour', models.TimeField()),
                ('breaks', models.IntegerField()),
                ('lunchs', models.IntegerField()),
                ('lunchBool', models.BooleanField()),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TranslatedQuestion',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('description', models.CharField(max_length=250)),
                ('idiom', models.IntegerField(default=1, choices=[(1, b'es'), (2, b'pt-br')])),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('question', models.ForeignKey(to='home.Question')),
            ],
        ),
        migrations.AddField(
            model_name='machinetask',
            name='task',
            field=models.ForeignKey(to='home.Task'),
        ),
        migrations.AddField(
            model_name='machineservice',
            name='service',
            field=models.ForeignKey(to='home.ServiceCategory'),
        ),
        migrations.AddField(
            model_name='machinequalification',
            name='qualification',
            field=models.ForeignKey(to='home.Qualification'),
        ),
        migrations.AddField(
            model_name='machinechecklist',
            name='question',
            field=models.ForeignKey(to='home.Question'),
        ),
        migrations.AddField(
            model_name='machine',
            name='manufacturer_model',
            field=models.ForeignKey(to='home.ManufacturerModel'),
        ),
        migrations.AddField(
            model_name='machine',
            name='repair_shop',
            field=models.ForeignKey(blank=True, to='home.RepairShop', null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='shop',
            field=models.ForeignKey(blank=True, to='home.Shop', null=True),
        ),
        migrations.AddField(
            model_name='implementtask',
            name='machine_task',
            field=models.ForeignKey(to='home.MachineTask'),
        ),
        migrations.AddField(
            model_name='implementtask',
            name='task',
            field=models.ForeignKey(to='home.Task'),
        ),
        migrations.AddField(
            model_name='implementservice',
            name='service',
            field=models.ForeignKey(to='home.ServiceCategory'),
        ),
        migrations.AddField(
            model_name='implementqualification',
            name='qualification',
            field=models.ForeignKey(to='home.Qualification'),
        ),
        migrations.AddField(
            model_name='implementchecklist',
            name='question',
            field=models.ForeignKey(to='home.Question'),
        ),
        migrations.AddField(
            model_name='implement',
            name='manufacturer_model',
            field=models.ForeignKey(to='home.ManufacturerModel'),
        ),
        migrations.AddField(
            model_name='implement',
            name='repair_shop',
            field=models.ForeignKey(blank=True, to='home.RepairShop', null=True),
        ),
        migrations.AddField(
            model_name='implement',
            name='shop',
            field=models.ForeignKey(blank=True, to='home.Shop', null=True),
        ),
        migrations.AddField(
            model_name='fieldlocalization',
            name='gps',
            field=models.ForeignKey(to='home.GPS'),
        ),
        migrations.AddField(
            model_name='employeetask',
            name='task',
            field=models.ForeignKey(to='home.Task'),
        ),
        migrations.AddField(
            model_name='employeequalifications',
            name='qualification',
            field=models.ForeignKey(to='home.Qualification'),
        ),
        migrations.AddField(
            model_name='employeeattendancechecklist',
            name='question',
            field=models.ForeignKey(to='home.Question'),
        ),
        migrations.AddField(
            model_name='employeeattendance',
            name='group',
            field=models.ForeignKey(blank=True, to='home.Group', null=True),
        ),
        migrations.AddField(
            model_name='confirmationcheck',
            name='attendance',
            field=models.ForeignKey(to='home.EmployeeAttendance'),
        ),
        migrations.AddField(
            model_name='confirmationcheck',
            name='question',
            field=models.ForeignKey(to='home.AttendanceChecklist'),
        ),
        migrations.AddField(
            model_name='break',
            name='attendance',
            field=models.ForeignKey(to='home.EmployeeAttendance'),
        ),
        migrations.AddField(
            model_name='beacongps',
            name='gps',
            field=models.ForeignKey(to='home.GPS'),
        ),
        migrations.AddField(
            model_name='appendixtask',
            name='task',
            field=models.ForeignKey(to='home.Task'),
        ),
    ]
